AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: Todo
      Runtime: go1.x
      Architectures:
        - x86_64
